### ISSUE TITLE
Tech reborn solar panel causes server freeze on chunk load

### ISSUE THREAD

**Issue by sdaugherty** [Fwogcraft/fwogkit#3]
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/5/20 7:59 PM
Description: Watching Server

java.lang.Error
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at net.minecraft.class_1255.method_20813(class_1255.java:139)
        at net.minecraft.class_1255.method_18857(class_1255.java:129)
        at net.minecraft.class_3215.method_12121(class_3215.java:139)
        at net.minecraft.class_1937.method_8402(class_1937.java:180)
        at net.minecraft.class_4538.method_22342(class_4538.java:108)
        at net.minecraft.class_1937.method_8497(class_1937.java:175)
        at net.minecraft.class_1937.method_8320(class_1937.java:381)
        at techreborn.blockentity.generator.SolarPanelBlockEntity.updatePanel(SolarPanelBlockEntity.java:79)
        at techreborn.blockentity.generator.SolarPanelBlockEntity.onLoad(SolarPanelBlockEntity.java:244)
        at net.minecraft.class_1937.handler$zdc000$chainmail_addBlockEntity(class_1937.java:2313)
```

**Comment by sdaugherty** [comment]
turns out this is a mod incompatability between expandedstorage fabric 5.0.1 and techreborn, downgraded expandedstorage to a 3.x version on the server - not releasing a new pack because this doesn't break clients and there will probably be a new expandedstorage release soon that fixes this properly
